lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-template-nfcore_logo_light.png
  - docs/images/nf-core-template-nfcore_logo_light.png
  - docs/images/nf-core-template-nfcore_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/CONTRIBUTING.md
  - .github/.dockstore.yml
  - .gitignore
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - conf/igenomes.config
  - conf/igenomes.config
  - .editorconfig
  - .prettierignore
  - .prettierrc.yml
  - LICENSE
  - assets/email_template.html
  - assets/email_template.txt
  - assets/sendmail_template.txt
  - CITATIONS.md
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-template_logo_light.png
  - docs/images/nf-core-template_logo_light.png
  - docs/images/nf-core-template_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows/branch.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - .github/CONTRIBUTING.md
  - .github/.dockstore.yml
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - process.cpus
  - process.memory
  - process.time
  - custom_config
  readme:
  - nextflow_badge
nf_core_version: 2.14.1
repository_type: pipeline
template:
  prefix: ferlab
  skip:
  - github
  - ci
  - github_badges
  - igenomes
  - nf_core_configs
